version: '3.9'
services:
  server:
    build: .
    ports:
      - '5001:5001'
    environment:
      PORT: 5001
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
      - redis

  db:
    container_name: shopDB
    image: 'postgres'
    ports:
      - '5444:5432'
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    ports:
      - '6380:6379'
    volumes: 
      - ./redisCache:/data
